allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - lucide-react@1.40.0
  - vitest@5.0.0
