export const ATTENTION_REASON_CODES = [
  "NEW_SINCE_LAST_SEEN",
  "PRICE_TARGET_NEAR_ENTERED",
  "PRICE_TARGET_CROSSED_ABOVE",
  "PRICE_TARGET_CROSSED_BELOW",
  "EARNINGS_EVENT_MATCHED",
  "TECHNICAL_SETUP_MATCHED",
  "DRIVER_EVENT_MATCHED",
  "DIVIDEND_EVENT_MATCHED",
  "COMPANY_EVENT_MATCHED",
  "UNUSUAL_PRICE_MOVE",
  "UNUSUAL_VOLUME",
  "MATERIAL_MARKET_EVENT",
  "MULTIPLE_SIGNALS",
  "DATA_FRESH",
  "DATA_DELAYED",
] as const;

export type AttentionReasonCode = (typeof ATTENTION_REASON_CODES)[number];
